### ISSUE TITLE
Error pointing to NPM environment issue

### ISSUE THREAD

**Issue by j-byrnes** [devops-mindset/variable-group-formatter#8]
Hello,
I'm in the process of creating a pipeline that I can use to manage azure keyvault values and secrets with ADO Pipeline Library Variable Groups. I found a thread where you posted your ADO extension as a response and wanted to see if I could use it in my pipeline.

However, I get the error below when executing my pipeline. It appears to point to a possible Node environment issue on runner.

I based my pipeline on the thread and example you provided, but no luck. Is it expected that I run/install a certain npm/Node environment setup first?

Pipeline
```yaml
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: ReadVars
  jobs:
  - job: ReadVars_Job1
    steps:
    - task: VariableGroupFormatter@0
      inputs:
        variableGroupID: '1'
        outputFormat: 'JSON'
        name: variableGroup
        displayName: "Format variables"

    - task: PowerShell@2
      displayName: 'List Variables'
      inputs:
        targetType: 'inline'
        script: |
            $varablesFromVariableGroup = '$(variableGroup.formattedVariables)'
          
            $jsonVarImport = ConvertFrom-Json -InputObject $varablesFromVariableGroup
          
            foreach ($variable in $jsonVarImport) {
              Write-Host "Variable '$($variable.name):' $($variable.value)"
            }

```

Pipeline Error
```
2023-06-22T18:54:58.6473794Z ##[section]Starting: VariableGroupFormatter
2023-06-22T18:54:58.6477399Z ==============================================================================
2023-06-22T18:54:58.6477643Z Task         : Variable Group Formatter
2023-06-22T18:54:58.6477704Z Description  : Formats the variables in a variable group to differents formats to be used in a pipeline.
2023-06-22T18:54:58.6477818Z Version      : 0.11.0
2023-06-22T18:54:58.6477868Z Author       : Devops Mindset
2023-06-22T18:54:58.6477920Z Help         : 
2023-06-22T18:54:58.6477962Z ==============================================================================
2023-06-22T18:54:58.8910620Z internal/modules/cjs/loader.js:638
2023-06-22T18:54:58.8911333Z     throw err;
2023-06-22T18:54:58.8911556Z     ^
2023-06-22T18:54:58.8911695Z 
2023-06-22T18:54:58.8912351Z Error: Cannot find module 'azure-pipelines-task-lib'
2023-06-22T18:54:58.8912646Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-06-22T18:54:58.8912955Z     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-06-22T18:54:58.8913313Z     at Module.require (internal/modules/cjs/loader.js:692:17)
2023-06-22T18:54:58.8914731Z     at require (internal/modules/cjs/helpers.js:25:18)
2023-06-22T18:54:58.8915206Z     at Object.<anonymous> (/home/vsts/work/_tasks/VariableGroupFormatter_91cabf98-0445-4e6b-95e6-52c74f425e8c/0.11.0/index.js:31:12)
2023-06-22T18:54:58.8915556Z     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-06-22T18:54:58.8915833Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-06-22T18:54:58.8916117Z     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-06-22T18:54:58.8916382Z     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-06-22T18:54:58.8916659Z     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-06-22T18:54:58.9077008Z ##[error]Exit code 1 returned from process: file name '/home/vsts/agents/3.220.5/externals/node10/bin/node', arguments '"/home/vsts/work/_tasks/VariableGroupFormatter_91cabf98-0445-4e6b-95e6-52c74f425e8c/0.11.0/index.js"'.
2023-06-22T18:54:58.9089216Z ##[section]Finishing: VariableGroupFormatter
```

**Comment by Strovsk** [comment]
## Solved

> The problem was I'm not installed NodeJs/NPM in my Deploy Environment VM

Same here. Just solve it in my case.
The problem occurred when I'm installed this extension in a VM located on a **Deploy Environment** (I think so it will works for self-hosted VMs).

To solve it, just enter in the task location on VM and run `npm install`.

## More details
When installing an agent in VM, the pipelines provider will make an structure ([see here](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/jobdirectories.md)) which stored in *~/azagent* by default when you install Azure integration.

The structure below was adapted by me ([see original](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/jobdirectories.md#build)). This is created inside *azagent* installation:
```
_work
│
├───1
│   ├───a
│   ├───b
│   ├───s
│   └───TestResults
├───2
│   ├───a
│   ├───b
│   ├───s
│   ├───TestResults
│   └─── >>> _tasks <<<
└───SourceRootMapping
    │   Mappings.json
    ├───7ca83873-9ab2-43be-86ac-bfb844bf5232
    │   ├───11
    │   │       SourceFolder.json
    │   └───7
    │           SourceFolder.json
    └───GC
```
The problem was I'm not installed NodeJs in my VM. So, after install, just enter in my AzAgent installation and run:

``` bash
cd /path/to/azagent/_work/_tasks/VariableGroupFormatter_someNumberId
npm install
```
